languageCode: en-us
theme: PaperMod
paginate: 100
enableRobotsTXT: true
enableGitInfo: true

params:
  defaultTheme: dark
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  mainSections:
    - posts
  assets:
    disableHLJS: true
  homeInfoParams:
    Title: The Best Wordpress Site
    Content: "**Wordpress is free, popular, and deeply flawed.**
    In a perfect world we'd all be writing web pages using a simplified descendant of HTML but in this world we're all using Wordpress.
    How can a sysadmin run this aging and inefficient website software to provide the best possible user experience on the inexpensive infrastrucuture that our clients can afford?
    I have been trying to answer that question since 2015, and this blog is a record of my findings."

  socialIcons: # optional
    - name: "bitcoin"
      url: "https://btcpay737660.lndyn.com/payment-requests/b56ac8bb-e25c-4f31-99c4-b47f348f0a17"
    - name: "github"
      url: "https://github.com/thebestwp/thebestwordpress"
    - name: "soundcloud"
      url: "https://youtu.be/dQw4w9WgXcQ"


menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 10

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: true
  youtube:
    disable: true

#markup:
#  goldmark:
#    renderer:
#      unsafe: true
